workflows:
    build:
        environment:
            flutter: 2.10.5
        scripts:
            -flutter pub get
            -flutter build appbundle --release
        artifacts:
            -build/**/*.aab